WebsiteBVXK/WebsiteBVXK/Pages/KhachHang/Giuong.cshtml.cs
using BVXK.Application.GetDonHangs;
using BVXK.Application.GetXes;
using BVXK.Application.GetCtDonHangs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BVXK.Domain.Infrastructure;
using BVXK.Domain.Models;
using BVXK.Domain.Enums;
using WebsiteBVXK.Infrastructure;

namespace WebsiteBVXK.Pages.KhachHang
{
    public class GiuongModel : PageModel
    {
        private ITicketManager _ticketManager;
        private IXeManager _xeManager;
        private IDonHangManager _donHangManager;
        private ICtDonHangManager _ctDonHangManager;
        private ILichTrinhManager _lichTrinhManager;
        private ISessionManager _sessionManager;
        public int soLuongGhe { get; set; }
        public List<int> gheDaDat { get; set; }
        public List<int> gheDangChon { get; set; }
        public VeXe selected { get; set; }
        public List<GheModel> ghes { get; set; }
        [BindProperty]
        public string tang { get; set; }
        public string ghe { get; set; }
        public GiuongModel(
            ITicketManager ticketManager,
            ICtDonHangManager ctDonHangManager,
            IDonHangManager donHangManager,
            IXeManager xeManager,
            ILichTrinhManager lichTrinhManager, ISessionManager sessionManager)
        {
            _ticketManager = ticketManager;
            _ctDonHangManager = ctDonHangManager;
            _donHangManager = donHangManager;
            _xeManager = xeManager;
            _lichTrinhManager = lichTrinhManager;
            _sessionManager = sessionManager;

            tang = "Tầng Dưới";
            ghes = new List<GheModel>();
            gheDaDat = new List<int>();
            gheDangChon = _sessionManager.GetGheChon();

            selected = _sessionManager.GetVeResult();
            var idXe = _lichTrinhManager.GetLichTrinhById(selected.IdLichTrinh, x => x.IdXe);
            var loaiXe = (int)_xeManager.GetXeById(idXe, x => x.LoaiXe);
            soLuongGhe = loaiXe == (int)LoaiXe.Ngoi ? 40 : 32;
            var donHangs = _donHangManager.GetDonHangByIdVe(selected.IdVe, x => x.IdDonHang);

            donHangs.ToList().ForEach(donHang =>
            {
                gheDaDat.AddRange(_ctDonHangManager.GetCtDonHangByIdDonHang(donHang, x => x.SoGhe));
            });

            for (int i = 0; i < soLuongGhe; i++)
            {
                ghes.Add(new GheModel
                {
                    index = i,
                    isPick = 0,
                });
            }

            foreach (int index in gheDaDat)
            {
                ghes[index].isPick = -1;
            }
            if(gheDangChon != null)
            {
                foreach (int index in gheDangChon)
                {
                    ghes[index].isPick = 1;
                }
            }
            
        }

        public string GetViTri()
        {
            gheDangChon = _sessionManager.GetGheChon();

            if(gheDangChon == null)
                return null;

            if (gheDangChon.Count <= 0)
                return "";

            string res = "";

            foreach (int i in gheDangChon)
            {
                var _i = i;
                if (i >= soLuongGhe / 2)
                {
                    _i -= soLuongGhe / 2;
                }

                switch (_i % 3)
                {
                    case 0:
                        res += "A";
                        break;
                    case 1:
                        res += "B";
                        break;
                    default:
                        res += "C";
                        break;
                }

                var y = _i / 3;

                if (i < soLuongGhe / 2)
                {
                    res += (y * 2 + 1).ToString();
                }
                else
                {
                    res += (y * 2 + 2).ToString();
                }

                res += ", ";
            }

            return res.Substring(0, res.Length - 2);
        }
        public void OnPostClickGhe(int id)
        {
            if (!ghes.Any())
                return;


            var res = gheDaDat.Where(x => x == id).ToList();

            var res2 = gheDangChon.Where(x => x == id).ToList();

            if (res2.Count != 0)
            {
                ghes[id].isPick = 0;
                gheDangChon.Remove(id);
                _sessionManager.RemoveGheChon(id);
                //_donHangManager.setGheDangChon(gheDangChon);
                return;
            }

            if(res.Count == 0)
            {
                ghes[id].isPick = 1;
                gheDangChon.Add(id);
                _sessionManager.AddGheChon(id);
                //_donHangManager.setGheDangChon(gheDangChon);
                return;
            }
        }

        public class GheModel
        {
            public int index { get; set; }
            public int isPick { get; set; }
        }
        public IActionResult OnPost()
        {
            _donHangManager.setGhe(GetViTri());
            if(gheDangChon.Count == 0)
                return Page();
            return RedirectToPage("/KhachHang/ThongTinKhachHang");
        }
    }
}

WebsiteBVXK/WebsiteBVXK/Pages/KhachHang/GiuongLimousine.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebsiteBVXK.Pages.KhachHang
{
    public class GiuongLimousineModel : PageModel
    {
    }
}

WebsiteBVXK/WebsiteBVXK/Pages/KhachHang/ThongTinKhachHang.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using BVXK.Application;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BVXK.Domain.Models;
using BVXK.Domain.Infrastructure;

namespace WebsiteBVXK.Pages.KhachHang
{
    public class ThongTinKhachHangModel : PageModel
    {
        private ISessionManager _sessionManager;

        public ThongTinKhachHangModel(ISessionManager sessionManager)
        {
            _sessionManager = sessionManager;
        }

        [BindProperty]
        public string tenkhach { get; set; }
        [BindProperty]
        public string sdt { get; set; }
        [BindProperty]
        public string email { get; set; }
        [BindProperty]
        public string cmnd { get; set; }
        [BindProperty]
        public string ghichu { get; set; }
         
        public IActionResult OnPost([FromServices] CustomerDetail customerDetail)
        {
            Customer customer = new Customer(tenkhach, sdt, email, cmnd);
            _sessionManager.AddCustomerInformation(customer);

            return RedirectToPage("/KhachHang/XacNhanThongTin");
        }
    }
}

WebsiteBVXK/WebsiteBVXK/Pages/KhachHang/ThongTinVe.cshtml.cs
using BVXK.Application.FindLichTrinh;
using BVXK.Application.Tickets;
using BVXK.Domain.Enums;
using BVXK.Domain.Infrastructure;
using BVXK.Domain.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebsiteBVXK.Infrastructure;

namespace WebsiteBVXK.Pages
{
    public class ThongTinVeModel : PageModel
    {
        public List<ThongTinVeViewModel> Titles { get; set; }
        private ILichTrinhManager _lichTrinhManager;
        private ITicketManager _ticketManager;
        private IXeManager _xeManager;
        private ISessionManager _sessionManager;
        public ThongTinVeModel(ILichTrinhManager lichTrinhManager, ITicketManager ticketManager, IXeManager xeManager, ISessionManager sessionManager)
        {
            _lichTrinhManager = lichTrinhManager;
            _ticketManager = ticketManager;
            _xeManager = xeManager;

            var res = _lichTrinhManager.GetFindResults();

            Titles = res.Select(x =>
            {

                var ticket = _ticketManager.GetTicketByIdLichTrinh(x.IdLichTrinh, _x => _x).FirstOrDefault();

                if (ticket == null)
                {
                    return null;
                }

                var xe = _xeManager.GetXeById(x.IdXe, _x => _x);

                int soghe = 0;

                switch (xe.LoaiXe)
                {
                    case (int?)LoaiXe.Ngoi:
                        soghe = 40;
                        break;
                    default:
                        soghe = 32;
                        break;
                }
                return new ThongTinVeViewModel
                {
                    DiemDen = x.NoiDen,
                    DiemDi = x.NoiXuatPhat,
                    GioDen = x.NgayDen.GetValueOrDefault().ToString("hh:mm"),
                    GioDi = x.NgayDi.GetValueOrDefault().ToString("hh:mm"),
                    GiaVe = (decimal)ticket.GiaVe,
                    LoaiXe = xe.LoaiXe == (int)LoaiXe.Ngoi ? "Xe Thường" : "Giường Vip",
                    idVe = ticket.IdVe,
                    SoGhe = soghe,
                };

            }).ToList();

            for (int i = 0; i < Titles.Count; i++)
            {
                var title = Titles[i];
                if (title == null)
                {
                    Titles.RemoveAt(i);
                }
            }
            _sessionManager = sessionManager;
        }

        public class ThongTinVeViewModel
        {
            public ThongTinVeViewModel()
            {
                DiemDen = "";
                DiemDi = "";
                GioDi = "";
                GioDen = "";
                LoaiXe = "";
                idVe = 0;
                SoGhe = 0;
                GiaVe = 0;
            }
            public string DiemDi { get; set; }
            public string DiemDen { get; set; }
            public string GioDi { get; set; }
            public string GioDen { get; set; }
            public string LoaiXe { get; set; }
            public decimal GiaVe { get; set; }
            public int SoGhe { get; set; }
            public int idVe { get; set; }
        }
        public IActionResult OnPostClick(int id, [FromServices] GetTicket getTicket)
        {
            var res = _ticketManager.GetTicketById(id, x => x);

            _sessionManager.AddVeResult(res);

            return RedirectToPage("/khachhang/giuong");
        }
    }
}

WebsiteBVXK/WebsiteBVXK/Pages/KhachHang/TimVe.cshtml.cs
using BVXK.Application.FindLichTrinh;
using BVXK.Application.TinhThanh;
using BVXK.Domain.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;

using System.Threading.Tasks;

namespace WebsiteBVXK.Pages
{
    public class TimVeModel : PageModel
    {
        public List<string> diemDi = TinhThanh.diemDi.ToList();
        public List<string> diemDen = TinhThanh.diemDen.ToList();
        private ISessionManager _sessionManager;
        private ILichTrinhManager _lichTrinhManager;
        public TimVeModel(ISessionManager sessionManager, ILichTrinhManager lichTrinhManager)
        {
            timVe = new TimVe();

            timVe.start = "Hà Nội";
            timVe.des = "Hồ Chí Minh";
            timVe.date = DateTime.Now;
            _sessionManager = sessionManager;
            _lichTrinhManager = lichTrinhManager;
        }
        [BindProperty]
        public TimVe timVe { get; set; }

        public class TimVe
        {
            public string start { get; set; }
            public string des { get; set; }
            public DateTime date { get; set; }
        }

        public IActionResult OnPost([FromServices] FindLichTrinh findLichTrinh)
        {
            var res = _lichTrinhManager.FindLichTrinh(timVe.start, timVe.des, timVe.date, x => x); //findLichTrinh.Do(timVe.start, timVe.des, timVe.date);

            if(res.Count() > 0)
            {
                _sessionManager.AddLichResult(res.ToList());
            }
            return RedirectToPage("/KhachHang/ThongTinVe");

            //return Page();
        }
    }
}

WebsiteBVXK/WebsiteBVXK/Pages/KhachHang/Giuong.cshtml
@page
@model WebsiteBVXK.Pages.KhachHang.GiuongModel
@{
	Layout = "_Layout";
	ViewData["Tittle"] = "Chọn Ghế";
}

<link rel="stylesheet" href="~/css/ghe.css"/>

<div class="bg"></div>
<div class="bg bg2"></div>
<div class="bg bg3"></div>
<div class="list-seats" >
	@*<div class="vexe-container">
		<label><b>CHỌN GHẾ:</b></label>
		<select id="chon-tang" asp-for="tang">
			<option>Tầng Dưới</option>
			<option>Tầng Trên</option>
		</select>
	</div>*@

	<ul class="showcase">
		<li>
			<div class="seat1"></div>
			<small style="color: rgb(128, 128, 128);">Trống</small>
		</li>
		<li>
			<div class="seat selected"></div>
			<small style="color: blue;">Đang Chọn</small>
		</li>
		<li>
			<div class="seat sold"></div>
			<small style="color: white;">Đã Đặt</small>
		</li>
	</ul>
	<div class="row">
	<div  class="container">
		<div class ="row" style="justify-content: space-around">
			<div>Tầng Dưới</div>
		</div>
		<div class ="row" style="justify-content: space-around">
			<div>A</div>
			<div>B</div>
			<div>C</div>
		</div>
		@{
			if(Model.ghes != null)
			{
				for (int i = 0; i <= Model.ghes.Count / 2; i = i + 3)
				{
					<div class="row">
						@for(int y = 0; y < 3; y++)
						{
							@if (i + y >= Model.ghes.Count / 2) continue;
							var state = Model.ghes[i + y].isPick;

							@if(state == 1){
								<form method="post" asp-route-id="@(i + y)" asp-page-handler="clickGhe">
									<button value=@(i + y) class="seat selected">@(i / 3 * 2 + 1)</button>
								</form>
							}
							else if(state == 0) {
								<form method="post" asp-route-id="@(i + y)" asp-page-handler="clickGhe">
									<button value=@(i + y) class="seat">@(i / 3 * 2 + 1)</button>
								</form>
							} else
							{
								<div>
									<button value=@(i + y) class="seat sold">@(i / 3 * 2 + 1)</button>
								</div>
							}
						}
					</div>
				}
			}
		}
	</div>
	<div  class="container">
		<div class ="row" style="justify-content: space-around">
			<div>Tầng Trên</div>
		</div>
		<div class ="row" style="justify-content: space-around">
			<div>A</div>
			<div>B</div>
			<div>C</div>
		</div>
		@{
			if(Model.ghes != null)
			{
				var start = Model.ghes.Count / 2;
				for (int i = 0; i <= Model.ghes.Count / 2; i = i + 3)
				{
					<div class="row">
						@for(int y = 0; y < 3; y++)
						{
							@if (start + i + y >= Model.ghes.Count) continue;
							var state = Model.ghes[start + i + y].isPick;

							@if(state == 1){
								<form method="post" asp-route-id="@(start + i + y)" asp-page-handler="clickGhe">
									<button value=@(start + i + y) class="seat selected">@(i / 3 * 2 + 2)</button>
								</form>
							}
							else if(state == 0){
								<form method="post" asp-route-id="@(start + i + y)" asp-page-handler="clickGhe">
									<button value=@(start + i + y) class="seat">@(i / 3 * 2 + 2)</button>
								</form>
							} else
							{
								<div>
									<button value=@(start + i + y) class="seat sold">@(i / 3 * 2 + 2)</button>
								</div>
							}
						}
					</div>
				}
			}
		}
	</div>
	</div>
	

	<p class="text">
		<ul>
			<li>Bạn đã chọn <b><span id="count">@Model.gheDangChon.Count</span></b> vé</li>
			<li>Số ghế của bạn <b><span id="count">@(this.Model.GetViTri())</span></b></li>
			<li>Tổng tiền của bạn <b><span id="total">@(((decimal)Model.selected.GiaVe * Model.gheDangChon.Count).ToString("N2"))<sup>đ</sup></span></b></li>
		</ul>
	</p>
	<br>
	<div class="btn12">
		<div>
			<button class="btn1">
				<a asp-page="/KhachHang/ThongTinVe">
					Quay Lại
				</a>
			</button>
		</div>
		<form method= "post" asp-route-id="next">
			<button class="btn2" type="submit">
				Tiếp tục
			</button>
		</form>
	</div>
</div>

WebsiteBVXK/WebsiteBVXK/Pages/KhachHang/GiuongLimousine.cshtml
@page
@model WebsiteBVXK.Pages.KhachHang.GiuongLimousineModel
@{
    Layout = "_Layout";
    ViewData["Tittle"] = "Chọn Ghế VIP";
}

<div class="vexe-container">
    <label><b>CHỌN GHẾ LIMOSINE:</b></label>
    <select id="loaighe">
        <option value="tangduoi">Tầng Dưới</option>
        <option value="tangtren">Tầng Trên</option>
    </select>
</div>

<ul class="showcase">
    <li>
        <div class="seat1"></div>
        <small style="color: rgb(128, 128, 128);">Trống</small>
    </li>
    <li>
        <div class="seat selected"></div>
        <small style="color: blue;">Đang Chọn</small>
    </li>
    <li>
        <div class="seat sold"></div>
        <small style="color: white;">Đã Đặt</small>
    </li>
</ul>

<div class="container">
    <div class="row">
        <div class="seat"></div>
        <div class="seat"></div>
    </div>
    <div class="row">
        <div class="seat"></div>
        <div class="seat"></div>
    </div>
    <div class="row">
        <div class="seat"></div>
        <div class="seat"></div>
    </div>
    <div class="row">
        <div class="seat"></div>
        <div class="seat"></div>
    </div>
    <div class="row">
        <div class="seat"></div>
        <div class="seat"></div>
    </div>
    <div class="row">
        <div class="seat"></div>
        <div class="seat"></div>
    </div>
    <div class="row">
        <div class="seat"></div>
        <div class="seat"></div>
    </div>
</div>

<p class="text">
    <ul>
        <li>Bạn đã chọn <b><span id="count">0</span></b> vé</li>
        <li>Số ghế của bạn <b><span id="count">A1</span></b></li>
        <li>Tổng tiền của bạn <b><span id="total">0<sup>đ</sup></span></b></li>
    </ul>
</p>
<br>
<div class="btn12">
    <div class="btn1">
        <button class="btn1" type="button" value="Quay lai">
            <a asp-page="/KhachHang/ThongTinVe" class="btn btn-primary">Quay Lại
            </a>
        </button>
    </div>
    <div class="btn2">
        <button class="btn2" type="button" value="Tiep tuc">
        <a asp-page="/KhachHang/ThongTinKhachHang">Tiếp Tục</a>
        </button>
    </div>
</div>

WebsiteBVXK/WebsiteBVXK/Pages/KhachHang/ThongTinChuyenKhoan.cshtml
@page
@{ 
    Layout = "_Layout";
    ViewData["Tittle"] = "Thông Tin Chuyển Khoản";
}

<link rel="stylesheet" href="~/css/ThongTinCK.css"/>

<div class="bg"></div>
<div class="bg bg2"></div>
<div class="bg bg3"></div>
<div class="text-box">
    <div class="hihi">Nhà xe Khánh Truyền</div>
    Xin chân thành cảm ơn quý khách vì đã tin yêu và sử dụng dịch vụ.<br>
    Quý khách vui lòng thanh toán qua thông tin sau. <br>
    <div class="thongtin">
        <div class="bank">
            Ngân hàng
        </div>
            Nông nghiệp và Phát triển nông thôn Việt Nam Agribank

        <div class="CTK">
            Chủ tài khoản:
        </div>
        Khánh Truyền

        <div class="STK">
            Số tài khoản: 
        </div>
        3701205097316

        <div class="ND">
            Nội dung chuyển khoản: 
        </div>
        Tên Khách Hàng + Số điện thoại + Số vé xe

    </div>
</div>

WebsiteBVXK/WebsiteBVXK/Pages/KhachHang/ThongTinKhachHang.cshtml
@page
@model WebsiteBVXK.Pages.KhachHang.ThongTinKhachHangModel
@{
    Layout = "_Layout";
    ViewData["Tittle"] = "Thông Tin Khách Hàng";
}

<link rel="stylesheet" href="/css/ThongTinKhach.css"/>

<div class="bg"></div>
<div class="bg bg2"></div>
<div class="bg bg3"></div>
<form method="post" class="banner">
    <div class="noidung">
        <div class="form">
            <h2><b>Thông Tin Khách Hàng</b></h2>
            <div>
                <div class="input-form">
                    <span>Tên Khách Hàng<sup>*</sup></span>
                    <input asp-for="tenkhach" type="text" placeholder="Nhập họ và tên của bạn" required/>
                </div>
                <div class="input-form">
                    <span>Số điện thoại<sup>*</sup></span>
                    <input type="text" asp-for="sdt" placeholder="Nhập số điện thoại của bạn" required/>
                </div>
                <div class="input-form">
                    <span>Email<sup>*</sup></span>
                    <input type="text" asp-for="email" placeholder="Nhập địa chỉ email của bạn" required/>
                </div>
                @*<div class="input-form">
                    <span>CMND/CCCD<sup>*</sup></span>
                    <input type="text" asp-for="cmnd" placeholder="Nhập CMND CCCD của bạn" required/>
                </div>*@
                @*<div class="note">
                    <span>Ghi chú</span>
                    <textarea name="ghichu" asp-for="ghichu" id="ghichu" cols="45" rows="4"></textarea>
                </div>*@
            </div>
            <div class="notes-container">
                <span class="title">Lưu ý</span> <br>
                <p class="txt">(*) Thông tin hành khách phải chính xác, nếu không sẽ không thể lên xe hoặc hủy/đổi vé.</p>
            </div>
            <div>
                <button class="btn3">   
			        <a asp-page="/KhachHang/XacNhanThongTin">
                    <span>Tiếp tục</span>
			        </a>
                </button>
            </div>
        </div>
    </div>
</form>

WebsiteBVXK/WebsiteBVXK/Pages/KhachHang/ThongTinVe.cshtml
@page
@model WebsiteBVXK.Pages.ThongTinVeModel
@{ 
    Layout = "_Layout";
    ViewData["Tittle"] = "Thông Tin Vé Xe";
}

<link rel="stylesheet" href="~/css/ThongTinVe.css"/>

<div class="bg"></div>
<div class="bg bg2"></div>
<div class="bg bg3"></div>
<div method="post" class="row" id ="ket-qua">
    <div class="thongtin">
        <h2><b>Chọn chuyến xe phù hợp</b></h2>
        <ul>
            @{
                if (Model.Titles != null && Model.Titles.Count > 0)
                {
                    foreach(var lichtrinh in Model.Titles)
                    {
                        <li class="card">
                            <div class="card-body">
                                <div class="details">
                                    <h1 class="card-title">
                                        <i class='bx bxs-log-in-circle bx-tada' ></i>
                                        @lichtrinh.DiemDi
                                        <span>&#10230</span>
                                        @lichtrinh.DiemDen
                                    </h1>
                                    <p class="card-text">
                                        <i class='bx bxs-time bx-tada' ></i>
                                        @lichtrinh.GioDi
                                        <span>&#10230</span>
                                        @lichtrinh.GioDen
                                    </p>
                                    <p class="card-text">
                                        <i class='bx bxs-bus bx-tada' ></i>
                                        Loại Xe: @lichtrinh.LoaiXe
                                    </p>
                                    <h5>
                                        <i class='bx bx-money-withdraw bx-tada' ></i>
                                        Giá vé: @lichtrinh.GiaVe.ToString("N2") 
                                        <sup>đ</sup>
                                    </h5>
                                </div>
                                <div class="contentbt">
                                    <form class="contentbt" method = "post" asp-page-handler="click" >
                                        <button name = "id" value = "@lichtrinh.idVe" type="submit">
                                            <span>Chọn Ghế</span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </li>
                    }
                }
                else
                {
                    <li>
                        <div>Không tìm thấy vé nào</div>
                        <button><a asp-page="/KhachHang/TimVe" class="btn btn-primary">Quay lại</a></button>
                    </li>
                }
            }
        </ul>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

WebsiteBVXK/WebsiteBVXK/Pages/KhachHang/TimVe.cshtml
@page
@model WebsiteBVXK.Pages.TimVeModel
@{ 
    Layout = "_Layout";
    ViewData["Tittle"] = "Tìm Vé Xe Khách";
}

<link rel="stylesheet" href="~/css/TimVe.css"/>

<div class="bg"></div>
<div class="bg bg2"></div>
<div class="bg bg3"></div>
<form method="post" class="banner" id = "tim-ve">
    <div class="contenttv">
        <div class="form">
            <h2><b>Tìm Kiếm Vé Xe</b></h2>
            <div>
                <div class="input-form">
                    <span>Chọn Điểm Đi</span>
                    <select asp-for="timVe.start">
                        @{
                            for(int tinh = 0; tinh < Model.diemDi.Count; tinh++)
                            {
                                <option>@Model.diemDi[tinh]</option>
                            }
                        }
                    </select>
                </div>
                <div class="input-form">
                    <span>Chọn Điểm Đến</span>
                    <select asp-for="timVe.des" >
                        @{
                            for(int tinh = 0; tinh < Model.diemDen.Count; tinh++)
                            {
                                <option>@Model.diemDen[tinh]</option>
                            }
                        }
                    </select>
                </div>
                <div class="input-form">
                    <span>Thời Gian Đi</span>
                    <input id="ngay-di" type="date" asp-for="timVe.date" />
                </div>
            </div>
            <div>
                <button class="buttontv">Tìm chuyến xe</button>
            </div>
        </div>
    </div>
</form>

<script>
    var today = new Date();
    var dd = today.getDate();
    var mm = today.getMonth() + 1; //January is 0!
    var yyyy = today.getFullYear();

    if (dd < 10) {
        dd = '0' + dd;
    }

    if (mm < 10) {
        mm = '0' + mm;
    }

    today = yyyy + '-' + mm + '-' + dd;

    document.getElementById("ngay-di").min = today;
</script>

WebsiteBVXK/WebsiteBVXK/Pages/KhachHang/XacNhanThongTin.cshtml
@page
@model WebsiteBVXK.Pages.KhachHang.XacNhanThongTinModel
@{
    Layout = "_Layout";
    ViewData["Tittle"] = "Xác Nhận Thông Tin";
}

<link rel="stylesheet" href="~/css/XacNhanTT.css"/>

<div class="bg"></div>
<div class="bg bg2"></div>
<div class="bg bg3"></div>
<div class="wrapper" id="send-mail">
    <div class="form">
    <div class="title">
        Xác nhận thông tin đặt vé
    </div>
    <div class="form">
        <div class="input-field">
            <label>Hành khách</label>
            <input type="text" class="input" readonly value = "@(Model.customer.name)"/>
        </div>
        <div class="input-field">
            <label>Số điện thoại</label>
            <input type="text" class="input" readonly value = "@(Model.customer.phone)"/>
        </div>
        <div class="input-field">
            <label>Email</label>
            <input type="text" class="input" readonly value = "@(Model.customer.email)"/>
        </div>
        @*<div class="input-field">
            <label>CMND/CCCD</label>
            <input type="text" class="input" readonly value = "@(Model.customer.id)"/>
        </div>*@
        <div class="input-field">
            <label>Chuyến</label>
            <input type="text" class="input" readonly value="@Model.chuyen"/>
        </div>
        <div class="input-field">
            <label>Ngày khởi hành</label>
            <input type="text" class="input" readonly value="@Model.ngayDi"/>
        </div>
        <div class="input-field">
            <label>Loại xe</label>
            <input type="text" class="input" readonly value="@Model.loaiXe"/>
        </div>
        <div class="input-field">
            <label>Số ghế</label>
            <input type="text" class="input" readonly value = "@(Model.seat)"/>
        </div>
        <div class="input-field">
            <label>Tổng tiền</label>
            <input type="text" class="input"  readonly value="@Model.tongtien"/>
        </div>
        @{
            if (Model.state)
            {
                <div>
                    Ghế đã có người đặt!
                </div>
            }
        }
        <form class="input-field" method="post">
            <button type="submit" class="btn">
                <span>Xác nhận</span>
            </button>
        </form>
    </div>
</div>

@section scripts{
    <script src="~/js/sendEmail.js"></script>
    <script src="~/js/emailTemp.js"></script>
    
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
   
}